### ISSUE TITLE
Tests panic

### ISSUE THREAD

**Issue by kevburnsjr** [elliotchance/mocksqs#3]
```
$ go test
go: downloading github.com/aws/aws-sdk-go v1.25.48
go: downloading github.com/elliotchance/orderedmap v1.2.0
go: extracting github.com/elliotchance/orderedmap v1.2.0
go: extracting github.com/aws/aws-sdk-go v1.25.48
go: finding github.com/elliotchance/orderedmap v1.2.0
go: finding github.com/aws/aws-sdk-go v1.25.48
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 60 [running]:
testing.tRunner.func1(0xc0001c7f00)
        c:/go/src/testing/testing.go:874 +0x3aa
panic(0x895bc0, 0xc0001a0420)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/elliotchance/mocksqs_test.TestQueue_Delete.func1(0xc0001c7f00)
        F:/web/junk/mocksqs/queue_test.go:26 +0x2ce
testing.tRunner(0xc0001c7f00, 0xc00019e550)
        c:/go/src/testing/testing.go:909 +0xd0
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x357
exit status 2
FAIL    github.com/elliotchance/mocksqs 0.076s
```
https://github.com/elliotchance/mocksqs/blob/master/queue_test.go#L26

**Comment by kevburnsjr** [comment]
After investigating, I suspect that the issue is related to `VisibleAfter`. I'm running the test from a windows command prompt (msysgit) which has poor sub-millisecond time resolution. This likely causes `ReceiveMessages` to return 0 results.  
https://github.com/elliotchance/mocksqs/blob/master/receive.go#L38

Working on a fix now.
